<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>nz.ac.auckland</groupId>
    <artifactId>project-a1-root</artifactId>
    <version>1.0</version>
    <packaging>pom</packaging>
    <modules>
        <module>server</module>
    </modules>

    <properties>
        <sonar.sources>server/src/main/java,client/src</sonar.sources>
        <sonar.tests>server/src/test/java,client/src</sonar.tests>
        <sonar.exclusions>/node_modules/,/target/,/dist/,/build/</sonar.exclusions>
    </properties>
</project>