sonar.projectKey=SOFTENG-310-Group-4_Project-A1-310-Group-4
sonar.organization=softeng-310-group-4
sonar.sources=src/main/java,../client/src
sonar.exclusions=**/test/**,**/target/**,**/node_modules/**